### ISSUE TITLE
iGibson installation 

### ISSUE THREAD

**Issue by scasalo** [AaronAnima/TarGF#3]
**I've tried to install iGibson, but this error appears:**

 packages
      ['pybullet_data', 'pybullet_envs', 'pybullet_examples', 'pybullet_robots', 'pybullet_utils', 'pybullet_data.configs', 'pybullet_data.configs_v2', 'pybullet_data.policies', 'pybullet_data.testdata', 'pybullet_data.configs_v2.base', 'pybullet_data.configs_v2.robots', 'pybullet_data.configs_v2.scenes', 'pybullet_data.configs_v2.tasks', 'pybullet_data.configs_v2.wrappers', 'pybullet_data.policies.ppo', 'pybullet_data.policies.ppo.minitaur_reactive_env', 'pybullet_data.policies.ppo.minitaur_trotting_env', 'pybullet_data.testdata.test_imu_state_estimator', 'pybullet_envs.agents', 'pybullet_envs.baselines', 'pybullet_envs.bullet', 'pybullet_envs.deep_mimic', 'pybullet_envs.examples', 'pybullet_envs.minitaur', 'pybullet_envs.prediction', 'pybullet_envs.stable_baselines', 'pybullet_envs.agents.ppo', 'pybullet_envs.agents.tools', 'pybullet_envs.deep_mimic.env', 'pybullet_envs.deep_mimic.gym_env', 'pybullet_envs.deep_mimic.learning', 'pybullet_envs.deep_mimic.learning.nets', 'pybullet_envs.deep_mimic.learning.solvers', 'pybullet_envs.minitaur.actuatornet', 'pybullet_envs.minitaur.agents', 'pybullet_envs.minitaur.envs', 'pybullet_envs.minitaur.envs_v2', 'pybullet_envs.minitaur.robots', 'pybullet_envs.minitaur.vision', 'pybullet_envs.minitaur.agents.baseline_controller', 'pybullet_envs.minitaur.agents.ppo', 'pybullet_envs.minitaur.agents.scripts', 'pybullet_envs.minitaur.agents.tools', 'pybullet_envs.minitaur.agents.trajectory_generator', 'pybullet_envs.minitaur.envs.env_randomizers', 'pybullet_envs.minitaur.envs_v2.env_wrappers', 'pybullet_envs.minitaur.envs_v2.evaluation', 'pybullet_envs.minitaur.envs_v2.examples', 'pybullet_envs.minitaur.envs_v2.scenes', 'pybullet_envs.minitaur.envs_v2.sensors', 'pybullet_envs.minitaur.envs_v2.tasks', 'pybullet_envs.minitaur.envs_v2.utilities', 'pybullet_envs.minitaur.robots.safety', 'pybullet_envs.minitaur.robots.utilities', 'pybullet_envs.minitaur.robots.safety.python', 'pybullet_robots.laikago', 'pybullet_robots.panda', 'pybullet_robots.xarm', 'pybullet_utils.examples']
      -----
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by scasalo** [comment]
I've installed cmake, it works but many other issues appears during installation, tbh, do not know if it related or not.. but what I know for sure that some packages needed to be downgraded such as gym

**Comment by AaronAnima** [comment]
Sry for the late reply, my gym version is 0.25.2 and it is compatible with igibson 1.0.3.

If you are trying to run the Room Rearrangement environment, feel free to email me :)

**Comment by hhh151671** [comment]
The link（https://www.dropbox.com/s/7j8f3dvn976hmaf/data.zip）seems to be dead. How to fix it?

**Comment by hhh151671** [comment]
> Sry for the late reply, my gym version is 0.25.2 and it is compatible with igibson 1.0.3.
> 
> If you are trying to run the Room Rearrangement environment, feel free to email me :)

The link（[https://www.dropbox.com/s/7j8f3dvn976hmaf/data.zip）seems](https://www.dropbox.com/s/7j8f3dvn976hmaf/data.zip%EF%BC%89seems) to be dead. How to fix it?

**Comment by AaronAnima** [comment]
The link is dead due to a licensing issue. You can contact me via email.
